### ISSUE TITLE
Loader with remote repo gives inconsistent results due to using branch

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/ubi-config#15]
The gitlab loader looks through the target repository using the gitlab repository/tree API.

It specifies the branch to use via 'ref' parameter.  Actually, this is broken since branches are mutable and can be changed at any time - including after ubi-config listed the files under the repo but before it downloaded them.

This could lead to weird unreproducible crashes when data changed while ubi-config was in progress.  For example:

1. Gitlab loader checks available files in master , _pre_load method
2. Somebody pushes a commit to master renaming files
3. load_all method crashes because some files mentioned in _files_branch_map are no longer available

Other weird bugs are also possible, e.g. load('file1') loads a file from commit 1 and load('file2') loads a file from commit 2.  So the UBI config didn't entirely use either commit 1 or commit 2 as the source for its config, but some undefined hybrid.  That makes it hard to reason about the behavior.

I think if it's going to support looking at a branch, the first thing it should do is resolve that branch to a specific SHA1.  It can then use that SHA1 for all later API queries.  That way you know you're looking at a snapshot of the git repo as at the time the loader was initialized, rather than reading data which is potentially changing while you read it.

**Comment by JayZ12138** [comment]
yeah, makes sense. I'll look into this ASAP
