### ISSUE TITLE
Loader with remote repo can miss configuration files

### ISSUE THREAD

**Issue by emilyzheng** [release-engineering/ubi-config#16]
get_file_list_api will return at most 20 results of remote repo if per_page is not specified in listing repository tree request according to [https://docs.gitlab.com/ee/api/repositories.html](https://docs.gitlab.com/ee/api/repositories.html). This will make some configuration files in remote repo can't be loaded if the repo has lots of files.

**Comment by JayZ12138** [comment]
For now, 20 results looks enough in our cases, I'll set it to a higher number and make it editable.

**Comment by JayZ12138** [comment]
set the default to 30, which should be enough. Also now user is able to specify the maximum number of files returned by passing per_page to get_loader(). 
Do you think it's enough to close this issue?

**Comment by emilyzheng** [comment]
I'm ok with the fix.

**Comment by rohanpm** [comment]
I don't think it was a good fix - it means that the caller has to know how many files are in the remote repo before safely using the API, doesn't it?  Isn't that rather inconvenient?  Anyway, can't the gitlab server return less files than you asked for?  That's how most pagination APIs work.

gitlab API docs suggest max per_page is 100, so if a repo has more than 100 files we can only read the first 100 files arbitrarily?  Seems pretty broken to me.  Shouldn't it be paginating over all the files?

**Comment by JayZ12138** [comment]
@rohanpm, 

Makes sense, I kinda misunderstood the doc about per-page. I'll submit a new patch later.
