### ISSUE TITLE
Failed to load configs with empty elements

### ISSUE THREAD

**Issue by emilyzheng** [release-engineering/ubi-config#28]
Loading configs which contain empty elements will raise error. E.g. when packages include is empty in below config file:
```
$ tail -5 /tmp/test.yaml 
packages:
  include:
  # Blacklist of packages to exclude
  exclude:
  - kernel

$ python
>>> from ubiconfig import get_loader
>>> config = get_loader("/tmp").load('test.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ubiconfig/_impl/loaders/local.py", line 33, in load
    return UbiConfig.load_from_dict(config_dict, file_name)
  File "/usr/lib/python2.7/site-packages/ubiconfig/config_types/__init__.py", line 32, in load_from_dict
    data.get('arches', []))
  File "/usr/lib/python2.7/site-packages/ubiconfig/config_types/packages.py", line 36, in __init__
    for package in include:
TypeError: 'NoneType' object is not iterable
```

**Comment by rbikar** [comment]
That's was caused by introduced by content in https://gitlab.cee.redhat.com/ubi/data/tree/crb8.
I will send email James Antill about that.

**Comment by rbikar** [comment]
afaict now it doesn't make sense to pass empty include in yaml file. Ubipop will effectively blacklist all packages, if include is empty.

**Comment by rohanpm** [comment]
Hmm... so here's an interesting question:

One of the points supposed to be covered by this library was to have a schema defined, and fail immediately when config doesn't match the schema.  That's supposed to clear up exactly this kind of confusion around whether fields are required or optional, and also could enable pre-commit checks to that mentioned git repo.

Looking at config_schema.json, it does seem to require 'include' to be an array, meaning the config should have been rejected according to schema:

```
    "packages": {
        "type": "object",
        "properties": {
            "include": {
                "type": "array",
                "items": {"type":"string"}
                },
            "exclude": {
                "type": "array",
                "items": {"type": "string"}
                }
            }
        }
```

include is type "array" and null/none shouldn't be allowed there.

Is the schema actually working or does it need updating?  It doesn't make sense to me, that we've gone to the effort of defining a schema, and yet config which is invalid could be loaded and cause crashes internally.

**Comment by rohanpm** [comment]
> Is the schema actually working or does it need updating?

No, the schema is not working at all :(  The validation function may as well be doing nothing.  This defeats the purpose of having a schema.  Filed https://github.com/release-engineering/ubi-config/issues/29.

https://github.com/release-engineering/ubi-config/issues/29 might effectively also solve this issue.
