### ISSUE TITLE
script shouldn't crash when config schema validation fails

### ISSUE THREAD

**Issue by JayZ12138** [release-engineering/ubi-config#31]
If there's schema error in a single config file, we shouldn't make the whole script crash during validation. Since we don't control the source of config file if it's from remote repo, it could take time to correct it.
Instead, the script should be able to skip that specific file and continue loading others. 

Acceptance criteria:
 ubiconfig can skip the config file with schema error and keep loading the rest files.

**Comment by JayZ12138** [comment]
@rbikar 
does this look fine to you?

**Comment by rbikar** [comment]
@JayZ12138 
Yes, it's good.
I'm just thinking that these kind of errors should be more visible so we can create easily ticket for responsible team of ubi config repo.
