### ISSUE TITLE
What's the point of "recursive" ?

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/ubi-config#46]
#### Summary

What's the point of the `recursive` argument in Loader.load_all?

If I'm writing code using ubiconfig, when should I pass recursive and when should I not?

If you look into real users of ubiconfig at time of writing, you'll find none of them pass the recursive argument.  Are those clients buggy or correct?

#### Issue Type

- Question / Support

#### Additional Information

`recursive` doesn't do anything at all for gitlab loader.  For local loader, it apparently makes the difference whether the loader descends into subdirectories, though it's unclear if this works (see issue https://github.com/release-engineering/ubi-config/issues/35).  I'm not seeing a clear case where I would *not* want it to descend into subdirectories.

**Comment by JayZ12138** [comment]
recursive is now removed from version 2.0.0.
